spring:
  application:
    name: test
  data:
    mongodb:
      username: username
      password: password
      database: db
      uri: uri
comparison:
  ignoredFields: "_id,last_updated"
  keyFields: "upc,product_id,catalog_type,country"
